In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import grangercausalitytests
from statsmodels.tsa.stattools import adfuller

In [ ]:
FEDFUNDS = pd.read_csv('FEDFUNDS_quarterly.csv')
DRCCLACBS = pd.read_csv('DRCCLACBS.csv')
CORCCACBS = pd.read_csv('CORCCACBS.csv')

obs_date = pd.to_datetime(FEDFUNDS['observation_date'])
obs_date = obs_date.dt.to_period('Q').dt.start_time
FEDFUNDS['observation_date'] = obs_date

In [ ]:
df_raw = pd.DataFrame()
df_raw['FEDFUNDS'] = FEDFUNDS['FEDFUNDS']
df_raw['Delinq'] = DRCCLACBS['DRCCLACBS']
df_raw['ChargeOff'] = CORCCACBS['CORCCACBS']
df_raw.set_index(obs_date, inplace = True)

In [ ]:
# Stationarity check
for col in df_raw.columns:
    if adfuller(df_raw[col])[1]>0.05:
        print(col)

FEDFUNDS
Delinq


In [ ]:
# Data Transformation for unstationary data
FEDFUNDS_diff = FEDFUNDS['FEDFUNDS'].diff().dropna()
Delinq_diff = DRCCLACBS['DRCCLACBS'].diff().dropna()

ChargeOff = CORCCACBS['CORCCACBS']
ChargeOff = ChargeOff.iloc[1:]
obs_date = obs_date.iloc[1:]

df_transformed = pd.DataFrame()
df_transformed['FEDFUNDS_diff'] = FEDFUNDS_diff
df_transformed['Delinq_diff'] = Delinq_diff
df_transformed['ChargeOff'] = ChargeOff
df_transformed.set_index(obs_date, inplace = True)

for col in df_transformed.columns:
    if adfuller(df_transformed[col])[1]>0.05:
        print(col)

In [ ]:
print(df_transformed)

                  FEDFUNDS_diff  Delinq_diff  ChargeOff
observation_date                                       
1994-04-01             0.726667        -0.31       3.02
1994-07-01             0.546667        -0.04       2.97
1994-10-01             0.680000         0.04       3.08
1995-01-01             0.643333         0.19       2.93
1995-04-01             0.210000         0.22       3.27
...                         ...          ...        ...
2023-10-01             0.070000         0.16       4.19
2024-01-01             0.000000         0.07       4.39
2024-04-01             0.000000         0.06       4.55
2024-07-01            -0.066667        -0.03       4.70
2024-10-01            -0.613333        -0.12       4.59

[123 rows x 3 columns]


In [ ]:
grangercausalitytests(df_transformed[['FEDFUNDS_diff', 'Delinq_diff']], maxlag = 4)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0055  , p=0.9411  , df_denom=119, df_num=1
ssr based chi2 test:   chi2=0.0056  , p=0.9402  , df=1
likelihood ratio test: chi2=0.0056  , p=0.9402  , df=1
parameter F test:         F=0.0055  , p=0.9411  , df_denom=119, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.8159  , p=0.4448  , df_denom=116, df_num=2
ssr based chi2 test:   chi2=1.7021  , p=0.4270  , df=2
likelihood ratio test: chi2=1.6902  , p=0.4295  , df=2
parameter F test:         F=0.8159  , p=0.4448  , df_denom=116, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.4849  , p=0.6934  , df_denom=113, df_num=3
ssr based chi2 test:   chi2=1.5448  , p=0.6720  , df=3
likelihood ratio test: chi2=1.5350  , p=0.6742  , df=3
parameter F test:         F=0.4849  , p=0.6934  , df_denom=113, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.2174  , p=0.9283  

{1: ({'ssr_ftest': (0.005481559028955236, 0.9411048154835302, 119.0, 1),
   'ssr_chi2test': (0.0056197495927104105, 0.9402425681211721, 1),
   'lrtest': (0.005619620163884065, 0.9402432549757515, 1),
   'params_ftest': (0.005481559028949973, 0.9411048154835302, 119.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (0.8158763441131065, 0.4447730182061146, 116.0, 2),
   'ssr_chi2test': (1.7020868558221702, 0.4269691878704649, 2),
   'lrtest': (1.6902264656141028, 0.4295087209789964, 2),
   'params_ftest': (0.8158763441130911, 0.44477301820612036, 116.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (0.4849003229299799, 0.6934427842154279, 113.0, 3),
   'ssr_chi2test': (1.5448151880955112, 0.6719662940251869, 3),
   'lrtest': (1.5349561530143205, 0.6742262838042822, 3),
   'params_ftest': (0.48490032292997426, 0.6934427842154309, 113.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0

In [ ]:
grangercausalitytests(df_transformed[['FEDFUNDS_diff', 'ChargeOff']], maxlag = 4)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.1988  , p=0.6565  , df_denom=119, df_num=1
ssr based chi2 test:   chi2=0.2038  , p=0.6517  , df=1
likelihood ratio test: chi2=0.2036  , p=0.6518  , df=1
parameter F test:         F=0.1988  , p=0.6565  , df_denom=119, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.0818  , p=0.9215  , df_denom=116, df_num=2
ssr based chi2 test:   chi2=0.1706  , p=0.9182  , df=2
likelihood ratio test: chi2=0.1705  , p=0.9183  , df=2
parameter F test:         F=0.0818  , p=0.9215  , df_denom=116, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.1213  , p=0.9474  , df_denom=113, df_num=3
ssr based chi2 test:   chi2=0.3865  , p=0.9430  , df=3
likelihood ratio test: chi2=0.3858  , p=0.9432  , df=3
parameter F test:         F=0.1213  , p=0.9474  , df_denom=113, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.2438  , p=0.9128  

{1: ({'ssr_ftest': (0.19875762003521788, 0.65653560561785, 119.0, 1),
   'ssr_chi2test': (0.20376831633862671, 0.6516962098583855, 1),
   'lrtest': (0.20359833539248484, 0.6518319171889626, 1),
   'params_ftest': (0.19875762003520767, 0.6565356056178607, 119.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (0.08177406261696589, 0.9215332037704073, 116.0, 2),
   'ssr_chi2test': (0.17059761339056678, 0.9182378677819816, 2),
   'lrtest': (0.17047746372423944, 0.91829303242568, 2),
   'params_ftest': (0.0817740626169564, 0.9215332037704133, 116.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (0.121308066996076, 0.9473857646165076, 113.0, 3),
   'ssr_chi2test': (0.38646817804059613, 0.9430234467618117, 3),
   'lrtest': (0.3858471874257816, 0.9431503650915003, 3),
   'params_ftest': (0.12130806699606451, 0.9473857646165127, 113.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 

In [ ]:
grangercausalitytests(df_raw[['FEDFUNDS', 'Delinq']], maxlag = 4)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=10.8870 , p=0.0013  , df_denom=120, df_num=1
ssr based chi2 test:   chi2=11.1592 , p=0.0008  , df=1
likelihood ratio test: chi2=10.6816 , p=0.0011  , df=1
parameter F test:         F=10.8870 , p=0.0013  , df_denom=120, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.4102  , p=0.6645  , df_denom=117, df_num=2
ssr based chi2 test:   chi2=0.8554  , p=0.6520  , df=2
likelihood ratio test: chi2=0.8524  , p=0.6530  , df=2
parameter F test:         F=0.4102  , p=0.6645  , df_denom=117, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.4909  , p=0.6893  , df_denom=114, df_num=3
ssr based chi2 test:   chi2=1.5631  , p=0.6678  , df=3
likelihood ratio test: chi2=1.5531  , p=0.6701  , df=3
parameter F test:         F=0.4909  , p=0.6893  , df_denom=114, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.3274  , p=0.8590  

{1: ({'ssr_ftest': (10.887001105046512, 0.001275189751967323, 120.0, 1),
   'ssr_chi2test': (11.159176132672673, 0.0008361704825501158, 1),
   'lrtest': (10.68164240667727, 0.0010820394917068514, 1),
   'params_ftest': (10.887001105046549, 0.0012751897519673028, 120.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (0.41016966212667433, 0.6644880350878803, 117.0, 2),
   'ssr_chi2test': (0.8553965603325515, 0.6520081089021885, 2),
   'lrtest': (0.8524117203273249, 0.6529819053216614, 2),
   'params_ftest': (0.4101696621266555, 0.6644880350878933, 117.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (0.49089244686522704, 0.6892963519966708, 114.0, 3),
   'ssr_chi2test': (1.5631048965971703, 0.6677841635634507, 3),
   'lrtest': (1.5530947450788517, 0.6700713994862622, 3),
   'params_ftest': (0.4908924468652048, 0.6892963519966858, 114.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [

In [ ]:
grangercausalitytests(df_raw[['FEDFUNDS', 'ChargeOff']], maxlag = 4)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=7.9609  , p=0.0056  , df_denom=120, df_num=1
ssr based chi2 test:   chi2=8.1600  , p=0.0043  , df=1
likelihood ratio test: chi2=7.9007  , p=0.0049  , df=1
parameter F test:         F=7.9609  , p=0.0056  , df_denom=120, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.2605  , p=0.7711  , df_denom=117, df_num=2
ssr based chi2 test:   chi2=0.5433  , p=0.7621  , df=2
likelihood ratio test: chi2=0.5421  , p=0.7626  , df=2
parameter F test:         F=0.2605  , p=0.7711  , df_denom=117, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.1549  , p=0.9263  , df_denom=114, df_num=3
ssr based chi2 test:   chi2=0.4934  , p=0.9203  , df=3
likelihood ratio test: chi2=0.4924  , p=0.9206  , df=3
parameter F test:         F=0.1549  , p=0.9263  , df_denom=114, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.2104  , p=0.9322  

{1: ({'ssr_ftest': (7.960929142979269, 0.005595664715834917, 120.0, 1),
   'ssr_chi2test': (8.15995237155375, 0.004282549594992467, 1),
   'lrtest': (7.900687717001745, 0.004941600596989742, 1),
   'params_ftest': (7.960929142979216, 0.0055956647158350485, 120.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (0.2605099103359273, 0.7711043426779648, 117.0, 2),
   'ssr_chi2test': (0.5432856249740705, 0.76212643452418, 2),
   'lrtest': (0.542079535116045, 0.7625861696123108, 2),
   'params_ftest': (0.2605099103359412, 0.7711043426779547, 117.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (0.15494650208042893, 0.9263120513170137, 114.0, 3),
   'ssr_chi2test': (0.49338228294031317, 0.9203428712617578, 3),
   'lrtest': (0.49237911610339324, 0.9205624682714232, 3),
   'params_ftest': (0.15494650208037733, 0.9263120513170494, 114.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0.,